### ISSUE TITLE
Use a monospace font for the textareas..

### ISSUE THREAD

**Issue by lipis** [ffflorian/sortjson.com#15]
What's the latest and greatest from each OS?

**Comment by bennyn** [comment]
Can be applied by switching from [TextField](https://material-ui.com/api/text-field/) component to [SyntaxHighlighter](https://github.com/conorhastings/react-syntax-highlighter) when rendering the output.

**Comment by lipis** [comment]
Even better.. colors are nice to have even in JSON files.. render them both the same..
