### ISSUE TITLE
Parse the input with Prettier before sorting

### ISSUE THREAD

**Issue by lipis** [ffflorian/sortjson.com#31]
```js
{
  'nice': 'mice',
    'hola': 'mola',
      foo: 'bar',
}
```

[Example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEmDkUCWYcOSuAtocQDQbbY4AWEANgIYnkvs1Z3YBmECKRwAjVgCccPAL4gqICAAcY+aAGdkoSRIgB3AAqSEmlKwBuEfABN5IURNZgA1nBgBlJU-xQA5shgJAFc4BQYYMmYAdQZ8eHUvIncTOPxzOIBPZHB1TQUfdTgJGANHXzJWZH5WZkKFACt1AA8AIUcXN3dWMjgAGR84Kpq6kEam9x9fZjgARSCIeCHa0JAvCUKJbMboOyUJHxgomxgGZAAOAAYFPYhCqMclbL24DfNBhQk4AEcg-E-S1jlSpIarLBSFCgBYIrdSTaZzBaDEHDFYwViiI7WE7IABMCkCrHwzEmAGEIGQKtkoNB3iAgoUACro0ygwoyGRAA)

People tend to do mistakes and that tool will correct them seamlesly :)

**Comment by ffflorian** [comment]
Fixed in [v1.3.0](https://github.com/ffflorian/sortjson.com/releases/tag/v1.3.0) with [json5](https://json5.org/).
